### ISSUE TITLE
Reverse lookup

### ISSUE THREAD

**Issue by pathcl** [skyline75489/SimpleDNS#13]
Lets say you have /etc/hosts

10.0.0.1 domain.tld

If you do:

$ dig -x 10.0.0.1

It should answer:

piwo:~ pathcl$ dig -x 10.0.0.1

; <<>> DiG 9.8.3-P1 <<>> -x 10.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30503
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;1.0.0.10.in-addr.arpa.		IN	PTR

;; ANSWER SECTION:
1.0.0.10.in-addr.arpa.	0	IN	PTR  domain.tld.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Jun 24 11:13:45 2017
;; MSG SIZE  rcvd: 81

I know maybe its just not a feature PTR :)

**Comment by skyline75489** [comment]
I'm not sure whether Twisted supports reverse DNS lookup. I'm take a look at it.

**Comment by pathcl** [comment]
http://twistedmatrix.com/documents/current/names/howto/client-tour.html#a-simple-example

**Comment by skyline75489** [comment]
Turns out it did, huh. Yet what is this for actually? And this tool is meant for breaking Internet censorship in China. I found no obvious reason for adding the ability to do reverse DNS lookup.
