### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by akar1nchan** [skyline75489/SimpleDNS#2]
123:~ 123$ python /Users/123/program/simpledns/simpledns/dnsproxy.py
Traceback (most recent call last):
  File "/Users/123/program/simpledns/simpledns/dnsproxy.py", line 47, in <module>
    from simpledns.util import is_address_validate
ImportError: No module named simpledns.util

**Comment by skyline75489** [comment]
现在应该没问题了，代码已经改过了

**Comment by akar1nchan** [comment]
thx~
