### ISSUE TITLE
Where is the fake IP list?

### ISSUE THREAD

**Issue by XIAOSpider97** [skyline75489/SimpleDNS#3]
The fake IPs have increased more, so we want to know where is the fake IP ignore list and we can edit it manually...

**Comment by skyline75489** [comment]
Actually, I stole it from other project like https://github.com/styx-hy/dnsmasq-chinadns/blob/master/spurious_ips.conf and https://github.com/clowwindy/ChinaDNS/blob/master/iplist.txt


https://github.com/clowwindy/ChinaDNS/blob/master/iplist.txt seems to be continually updating. You may want to check that out.
