### ISSUE TITLE
How to make this work with IPv6?

### ISSUE THREAD

**Issue by XIAOSpider97** [skyline75489/SimpleDNS#4]
We are all from CERNET2 with IPv6, and we rented a VPS @ Zhengzhou GIANT (景安), which provides IPv6 network.
How to make this works with both IPv4 and IPv6? 
-b 0.0.0.0 —— V4 only...
-b :: —— it won't crash, but cannot nslookup
-b [::] —— crash...

**Comment by skyline75489** [comment]
Sadly I don't have an IPv6 environment to add IPv6 support myself.

You may want to check out Twisted doc [here](https://twistedmatrix.com/trac/) to see if there is a way to do this.
