### ISSUE TITLE
IOError on OS X 10.11 el capitan

### ISSUE THREAD

**Issue by zwpaper** [skyline75489/SimpleDNS#5]
```
Traceback (most recent call last):
  File "/usr/local/bin/simpledns", line 7, in <module>
    from simpledns.dnsproxy import main
  File "/Library/Python/2.7/site-packages/simpledns/dnsproxy.py", line 75, in <module>
    GFW_LIST = read_iplist(IPLIST_PATH)
  File "/Library/Python/2.7/site-packages/simpledns/dnsproxy.py", line 70, in read_iplist
    with open(path) as f:
IOError: [Errno 2] No such file or directory: '/usr/local/etc/simpledns/iplist.txt'
```

已经 sudo 权限打开了，还是找不到文件，不知道这个 iplist.txt 是否是自己生成的？
我试了一下，自己从 ChinaDNS 中复制这个文件之后，可以运行了，我觉得有必须在 Usage 中说明一下

PS，用了 simple 之后速度慢好多，所以又放弃了

**Comment by i6941** [comment]
我也发现了个这个问题，应该是绝对路径被处理成了相对路径，/usr/local/etc/simpledns被建立在了/Library/Python/2.7/site-packages目录下

**Comment by skyline75489** [comment]
确实是少拷贝了两个文件，用的话显得慢太多，也是因为少了配置文件，导致国内国外的网站解析没有分开

**Comment by skyline75489** [comment]
看来我是好久没用 Pip 了，pip 的行为发生变化了 https://github.com/pypa/pip/issues/2874#issuecomment-109429489

**Comment by skyline75489** [comment]
pip 和 `setup.py` 行为不一致，我把 README 更新了，使用 `setup.py` 安装是 OK 的。
