### ISSUE TITLE
有几个建议

### ISSUE THREAD

**Issue by bao3** [skyline75489/SimpleDNS#6]
1. 可否增加一个自动更新 iplist.txt 功能，例如 simpledns 运行期间
2. *可否增加一个读取自定义 txt 的功能* （ 自己解决了，看到了` --hosts-file` ）
3. 可否增加一个配置文件，这样可以自定义监听端口，要设置的其他的参数。
4. 默认使用的上游的 DNS是啥。。有没有办法可以自己指定更换，比如  `202.141.176.93
202.141.162.123
202.38.93.153`  这几个本身就可以正常解析国外的网站，要是能指定 **多个**上游DNS 就好了

以上 4 个需求中，功能 3 是紧急且重要的，希望可以考虑早日实现。

**Comment by skyline75489** [comment]
感谢关注，这个项目我自己已经有一段时间没有维护了，有些功能我很早就想加入了（像配置文件）可惜一直比较忙，没有时间再投入到这个项目上了。如果有兴趣 PR 的话随时欢迎 :smile: 

默认的 DNS 是 OpenDNS ，也是一个能正常解析的上游 DNS，跟谷歌 8.8.8.8 类似。

**Comment by bao3** [comment]
@skyline75489 谢谢，已经更改成了 8.8.8.8 。只是我使用的时 mac ，似乎这个 simple dns这种同类程序 在 mac 上效用不大，除了 cache 国内的域名。

**Comment by skyline75489** [comment]
现在通过纯 DNS 想翻墙是比较困难的。需要配合别的工具。

我当时写这个时候在教育网内可以达到比较好的效果，能上 FB 和 Youtube。别的网络环境的话，仅仅做 DNS 的工作是肯定不够的。

**Comment by bao3** [comment]
只要能解析出正确的 DNS IP就已经是成功的一半了。 issue cloed ~ thanks
