### ISSUE TITLE
咨询：这个 DNS 如何自定规则？如何通过参数指定 iplist.txt 的路径？

### ISSUE THREAD

**Issue by ferocknew** [skyline75489/SimpleDNS#8]
如题

**Comment by skyline75489** [comment]
规则的话可以通过 dispatch.conf 来自定义，没有提供参数指定 iplist 路径的功能。

**Comment by ferocknew** [comment]
谢谢回复。

iplist 文件暂时通过 ln 解决问题，不过增加一个参数的确会很方便。
dispatch.conf，文件编写规则，没有在 README 里看到，有稍微简单点的说明么？

**Comment by skyline75489** [comment]
README 里其实提到了，使用的是 dnsmasq 的规则，支持了 address 和 server 这两种配置

**Comment by ferocknew** [comment]
明白了，我研究一下。

使用你这个 dns 的人多么？

**Comment by skyline75489** [comment]
这个项目是我两年前写的了，已经大概一年没维护了。当时在学校的时候我自己是用的，现在没有教育网环境其实用处已经不太大了。

**Comment by ferocknew** [comment]
其实本地 dns 的意义还是很大的，特别是放污染。

如果有时间，继续维护一定会非常棒的

**Comment by skyline75489** [comment]
这项目里面用的 iplist 已经 conf 来自于另一个项目 https://github.com/felixonmars/dnsmasq-china-list ，可以试着去更新一下新的地址列表。

**Comment by skyline75489** [comment]
现在这个列表变的有点大了，不知道会不会有性能问题...

**Comment by ferocknew** [comment]
你测测，怎么更新这个？是 cp 文件到某个目录么

**Comment by skyline75489** [comment]
就是这个 https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf 扔到 dispatch.conf 里

**Comment by ferocknew** [comment]
我是用 pip 安装的，dispatch 文件在哪儿呢？

**Comment by skyline75489** [comment]
/usr/local/etc/simpledns/dispatch.conf

**Comment by ferocknew** [comment]
我这个目录下只有

# yingjun @ YingjundeMacBook-Pro in /usr/local/etc/simpledns on git:master o [14:22:00] 
$ ll
total 8
drwxr-xr-x  4 yingjun admin 136  9 18 13:52 ./
drwxr-xr-x 26 yingjun admin 884  9 18 13:52 ../
-rw-r--r--  1 root    admin 180  9 18 13:52 cache.pk
lrwxr-xr-x  1 yingjun admin  58  9 18 13:52 iplist.txt -> /Users/yingjun/CloudStation/sync/tools/chinaDNS/iplist.txt

**Comment by ferocknew** [comment]
是新建一个空白的么？

**Comment by skyline75489** [comment]
在 Mac 上安装貌似有些问题.....你建一个试试吧...

**Comment by ferocknew** [comment]
已经新建一个，并且 ln 过去，只是不知道是不是调取了。
另外，发现在arm 上通过 pip 安装有问题，失败了
